In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('C:/Users/Mohamed Arshad/Desktop/Data Science -1/Deep Learning/News.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
missing_values=df.isnull().sum()

In [6]:
missing_percentage=(missing_values/len(df))*100

In [7]:
missing_info=pd.DataFrame({'Columns':missing_values.index,
                           'missing_numbers':missing_values.values,
                           'missing_percentage':['{:.3f}%'.format(val)for val in missing_percentage.values]})
missing_info

Columns  missing_numbers missing_percentage
0      id                0             0.000%
1   title              558             2.683%
2  author             1957             9.409%
3    text               39             0.188%
4   label                0             0.000%

In [8]:
df=df.dropna()

In [9]:
df.shape

(18285, 5)

In [10]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [11]:
messages=df.copy()

In [12]:
messages.shape

(18285, 5)

In [13]:
messages.reset_index(inplace=True)

In [14]:
messages.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [15]:
import re
import nltk

In [16]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [17]:
ps=PorterStemmer()

In [18]:
messages['title'][8]

'Obama’s Organizing for Action Partners with Soros-Linked ‘Indivisible’ to Disrupt Trump’s Agenda'

In [19]:
corpus=[]
for i in range(len(messages)):
    clean=re.sub('[^a-zA-Z]',' ',messages['title'][i])
    clean=clean.lower()
    clean=clean.split()
    clean=[ps.stem(word)for word in clean if word not in set(stopwords.words('english'))]
    clean=' '.join(clean)
    corpus.append(clean)
    

In [20]:
import tensorflow

In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
voc_size=5000

In [23]:
one_hot_encoding=[one_hot(input_text=word,n=voc_size)for word in corpus]

In [24]:
max_length = max((len(text)) for text in corpus)
print(max_length)

299


In [25]:
one_hot_encoding[10000:10020]

[[4254, 1623, 3831, 1768, 3130, 2747, 1928, 475, 4549, 205],
 [2738, 576, 1180, 2443, 4085, 444, 180, 2857],
 [3471, 1982, 3447, 3719, 997, 3374, 2054, 3042, 729],
 [292, 2654, 2794, 3314, 1589, 4758, 3853, 1845, 4591],
 [3730, 1822, 4191, 3887, 3707, 384, 1121, 1523, 1568],
 [3657, 2753, 2937, 4978, 1010, 82, 4043, 3954],
 [1951, 4313, 2110, 4461, 3853, 1845, 4591],
 [4789, 1739, 1650, 2313, 1890, 3479, 1510],
 [2676, 2925, 320, 3585, 2717, 1735, 2498, 793, 3608, 3624, 2060, 1568],
 [67, 1744, 1058, 4917, 275, 4584, 2072],
 [474, 4299, 1900, 2748, 2644, 1900, 4480, 3451, 1336, 2926, 1568],
 [1515, 1099, 3092, 2805, 2995, 3698, 2256, 3853, 1845, 4591],
 [3775, 4697, 1107, 3425, 3853, 1511, 2754, 3976],
 [3246, 4004, 1535, 3555, 4085, 54, 3380, 2027, 2889, 3853, 1845, 4591],
 [3660, 3704, 3894, 1844, 2132],
 [3908, 4834, 4044, 731, 4106, 593, 4132, 320],
 [566, 2366],
 [822, 1431],
 [2744, 4599, 1897, 4094, 1679, 3655, 3199, 2451],
 [2878, 2763, 3181, 2070, 213, 1326, 4707, 1626]]

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
sentences_length=50

In [28]:
padded=pad_sequences(sequences=one_hot_encoding,padding='pre',maxlen=sentences_length)

In [29]:
print(len(padded[3]))

50


In [30]:
padded[:10]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,  910, 1517, 3706, 2888,
        4538, 4829, 3427,  355, 4060, 3505],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3611,
        4097, 1545, 3050, 2753, 4332, 1568],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 19

In [31]:
y=df['label']

In [32]:
y.info()

<class 'pandas.core.series.Series'>
Index: 18285 entries, 0 to 20799
Series name: label
Non-Null Count  Dtype
--------------  -----
18285 non-null  int64
dtypes: int64(1)
memory usage: 285.7 KB


In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [34]:
embedding_vector_features=50

In [35]:
model=Sequential()

In [36]:
model.add(Embedding(input_dim=voc_size,output_dim=sentences_length,input_length=embedding_vector_features))
model.add(LSTM(units=100))
model.add(Dense(units=1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
import numpy as np

In [39]:
X=np.array(padded)
y=np.array(y)

In [40]:
X.shape

(18285, 50)

In [41]:
y.shape

(18285,)

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [44]:
X_train.shape

(12250, 50)

In [45]:
model.fit(x=X_train,y=y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 40ms/step - loss: 0.3210 - accuracy: 0.8520 - val_loss: 0.1937 - val_accuracy: 0.9193
Epoch 2/10
192/192 [==============================] - 6s 33ms/step - loss: 0.1313 - accuracy: 0.9506 - val_loss: 0.1934 - val_accuracy: 0.9213
Epoch 3/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0834 - accuracy: 0.9714 - val_loss: 0.2096 - val_accuracy: 0.9183
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0488 - accuracy: 0.9833 - val_loss: 0.2934 - val_accuracy: 0.9099
Epoch 5/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0261 - accuracy: 0.9921 - val_loss: 0.3157 - val_accuracy: 0.9145
Epoch 6/10
192/192 [==============================] - 7s 34ms/step - loss: 0.0164 - accuracy: 0.9949 - val_loss: 0.3835 - val_accuracy: 0.9115
Epoch 7/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0062 - accuracy: 0.9985 - val_loss: 0.4667 - val_accuracy: 0.9148

In [46]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [47]:
y_pred=model.predict(x_test)

189/189 [==============================] - 1s 6ms/step


In [48]:
y_pred=y_pred>0.5

In [49]:
confusion_matrix(y_test,y_pred)

array([[3119,  300],
       [ 260, 2356]], dtype=int64)

In [50]:
accuracy_score(y_test,y_pred)

0.9072079536039768

In [51]:
from keras.layers import Dropout

In [52]:
model1=Sequential()

In [53]:
model1.add(Embedding(input_dim=voc_size,output_dim=sentences_length,input_length=embedding_vector_features))
model1.add(Dropout(0.3))
model1.add(LSTM(units=100))
model1.add(Dropout(0.3))
model1.add(Dense(units=1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 50)            250000    
                                                                 
 dropout (Dropout)           (None, 50, 50)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               60400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [54]:
model1.fit(X_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 37ms/step - loss: 0.3219 - accuracy: 0.8502 - val_loss: 0.1887 - val_accuracy: 0.9186
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1402 - accuracy: 0.9436 - val_loss: 0.1899 - val_accuracy: 0.9203
Epoch 3/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0947 - accuracy: 0.9643 - val_loss: 0.2109 - val_accuracy: 0.9152
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0650 - accuracy: 0.9789 - val_loss: 0.2555 - val_accuracy: 0.9157
Epoch 5/10
192/192 [==============================] - 7s 37ms/step - loss: 0.0378 - accuracy: 0.9876 - val_loss: 0.2964 - val_accuracy: 0.9117
Epoch 6/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0264 - accuracy: 0.9909 - val_loss: 0.3211 - val_accuracy: 0.9077
Epoch 7/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0174 - accuracy: 0.9943 - val_loss: 0.4213 - val_accuracy: 0.9105

In [55]:
y_pred1=model1.predict(x_test)

189/189 [==============================] - 1s 6ms/step


In [56]:
y_pred1=y_pred1>0.5

In [57]:
confusion_matrix(y_test,y_pred1)

array([[3094,  325],
       [ 206, 2410]], dtype=int64)

In [58]:
accuracy_score(y_test,y_pred1)

0.912013256006628