In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('C:/Users/Mohamed Arshad/Desktop/Data Science -1/Deep Learning/News.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
missing_values=df.isnull().sum()

In [6]:
missing_percentage=(missing_values/len(df))*100

In [7]:
missing_info=pd.DataFrame({'Columns':missing_values.index,
                           'missing_numbers':missing_values.values,
                           'missing_percentage':['{:.3f}%'.format(val)for val in missing_percentage.values]})
missing_info

Columns  missing_numbers missing_percentage
0      id                0             0.000%
1   title              558             2.683%
2  author             1957             9.409%
3    text               39             0.188%
4   label                0             0.000%

In [8]:
df=df.dropna()

In [9]:
df.shape

(18285, 5)

In [10]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [11]:
messages=df.copy()

In [12]:
messages.shape

(18285, 5)

In [13]:
messages.reset_index(inplace=True)

In [14]:
messages.head(10)

index  id                                              title  \
0      0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1      1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2      2   2                  Why the Truth Might Get You Fired   
3      3   3  15 Civilians Killed In Single US Airstrike Hav...   
4      4   4  Iranian woman jailed for fictional unpublished...   
5      5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6      7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
7      9   9  A Back-Channel Plan for Ukraine and Russia, Co...   
8     10  10  Obama’s Organizing for Action Partners with So...   
9     11  11  BBC Comedy Sketch "Real Housewives of ISIS" Ca...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6               Alissa J. Rubin   
7  Megan Twohey and Scott Shane   
8                   Aaron Klein   
9               Chris Tomlinson   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  PARIS  —   France chose an idealistic, traditi...      0  
7  A week before Michael T. Flynn resigned as nat...      0  
8  Organizing for Action, the activist group that...      0  
9  The BBC produced spoof on the “Real Housewives...      0

In [15]:
import re
import nltk

In [16]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [17]:
ps=PorterStemmer()

In [18]:
messages['text'][8]

'Organizing for Action, the activist group that morphed from Barack Obama’s first presidential campaign, has partnered with the   Indivisible Project for “online trainings” on how to protest President Donald Trump’s agenda. [Last week, Breitbart News extensively reported that Indivisible leaders are openly associated with groups financed by billionaire George Soros.  Politico earlier this month profiled Indivisible in an article titled, “Inside the protest movement that has Republicans reeling. ”  The news agency not only left out the Soros links, but failed to note that the organizations cited in its article as helping to amplify Indivisible’s message are either financed directly by Soros or have close ties to groups funded by the billionaire, as Breitbart News documented. Organizing for Action (OFA) is a   community organizing project that sprung from Obama’s 2012 campaign organization, Organizing for America, becoming a nonprofit described by the Washington Post as “advocate[ing] fo

In [19]:
corpus=[]
for i in range(len(messages)):
    clean=re.sub('[^a-zA-Z]',' ',messages['text'][i])
    clean=clean.lower()
    clean=clean.split()
    clean=[ps.stem(word)for word in clean if word not in set(stopwords.words('english'))]
    clean=' '.join(clean)
    corpus.append(clean)
    

In [20]:
import tensorflow

In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
voc_size=5000

In [23]:
one_hot_encoding=[one_hot(input_text=word,n=voc_size)for word in corpus]

In [24]:
max_length = max((len(text)) for text in corpus)
print(max_length)

72006


In [25]:
one_hot_encoding[10000:10020]

[[4290,
  857,
  4970,
  784,
  3218,
  510,
  4434,
  721,
  3958,
  553,
  553,
  814,
  2392,
  1723,
  4714,
  3515,
  3958,
  3218,
  510,
  4290,
  857,
  4388,
  4970,
  2442,
  817,
  2823,
  1199,
  1480,
  4290,
  857,
  1832,
  1480,
  4712,
  1085,
  2851,
  773,
  4706,
  761,
  3339,
  4207,
  3002,
  3836,
  4970,
  784,
  1199,
  3532,
  784,
  2493,
  4841,
  2284,
  1218,
  3099,
  1832,
  4809,
  3218,
  4802,
  2750,
  3148,
  3664,
  590,
  3077,
  2507,
  2207,
  3218,
  510,
  4915,
  4809,
  450,
  4193,
  3218,
  4802,
  2320,
  4290,
  857,
  1298,
  1348,
  2003,
  4966,
  4841,
  4372,
  721,
  905,
  4290,
  857,
  3032,
  2928,
  3218,
  4915,
  4809,
  2045,
  2032,
  2680,
  654,
  3881,
  2773,
  4915,
  4809,
  4841,
  4453,
  3020,
  2402,
  1179,
  1252,
  3201,
  3098,
  1752,
  4802,
  3868,
  4806,
  697,
  3314,
  4890,
  1357,
  3480,
  1222,
  2928,
  3218,
  3480,
  2746,
  3014,
  784,
  2402,
  1488,
  4880,
  2448,
  2174,
  3920,
  3869,
 

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [87]:
sentences_length=50

In [88]:
padded=pad_sequences(sequences=one_hot_encoding,padding='pre',maxlen=sentences_length)

In [89]:
print(len(padded[3]))

50


In [90]:
padded[:10]

array([[4608,  184, 1663, 2182,  334, 2251, 2177, 1430,  266, 2756, 1585,
        4296,  144, 1430, 2756, 1585, 3155, 4464, 4535, 4158, 2103, 1779,
         326,  875, 1654, 2280, 4466, 3654, 4679, 4949, 3148, 3434,  185,
        1095,   53, 2337, 4158, 4122, 1059,   69,  291, 3548, 4880, 4754,
        2925, 3702,  711, 3657, 3439, 4880],
       [3293, 3833, 1997, 4402, 3098, 1239,  346, 1894, 2669,   64, 2742,
        4237,   64, 1100,   73, 3033,  599, 3977, 3014, 1894,  114, 4772,
        3397, 3459,  185, 3397, 3045,   64,  967,  863, 1425, 1028, 4594,
        1377, 2709, 3430, 2906, 2363, 1223, 4485, 1454, 2320, 4121, 3232,
        4472, 4621, 1454, 4216,  351, 3971],
       [ 660, 2036, 2772, 3583, 3326, 3285, 3558, 4234,  793, 4234, 1646,
         827, 4973, 1410, 1681, 4085, 1369, 1995, 2032, 2838,   55, 3061,
        4279,  599, 4391,  342, 3581, 3186, 1162,  949, 3427, 1816, 3401,
        3992, 2032, 4817, 2416, 1569,  225, 4688, 1166, 1793, 2680, 4436,
        4623,  607, 29

In [91]:
y=df['label']

In [92]:
y.info()

<class 'pandas.core.series.Series'>
Index: 18285 entries, 0 to 20799
Series name: label
Non-Null Count  Dtype
--------------  -----
18285 non-null  int64
dtypes: int64(1)
memory usage: 285.7 KB


In [93]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [94]:
embedding_vector_features=50

In [95]:
model=Sequential()

In [96]:
model.add(Embedding(input_dim=voc_size,output_dim=sentences_length))
model.add(LSTM(units=100))
model.add(Dense(units=1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [97]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, None, 50)          250000    
                                                                 
 lstm_3 (LSTM)               (None, 100)               60400     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [98]:
import numpy as np

In [99]:
X=np.array(padded)
y=np.array(y)

In [100]:
X.shape

(18285, 50)

In [101]:
y.shape

(18285,)

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [104]:
X_train.shape

(12250, 50)

In [105]:
model.fit(x=X_train,y=y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 11s 52ms/step - loss: 0.3877 - accuracy: 0.8179 - val_loss: 0.2816 - val_accuracy: 0.8805
Epoch 2/10
192/192 [==============================] - 10s 51ms/step - loss: 0.2014 - accuracy: 0.9249 - val_loss: 0.2649 - val_accuracy: 0.8827
Epoch 3/10
192/192 [==============================] - 11s 56ms/step - loss: 0.1340 - accuracy: 0.9522 - val_loss: 0.2908 - val_accuracy: 0.8885
Epoch 4/10
192/192 [==============================] - 11s 58ms/step - loss: 0.0838 - accuracy: 0.9711 - val_loss: 0.3420 - val_accuracy: 0.8749
Epoch 5/10
192/192 [==============================] - 10s 51ms/step - loss: 0.0534 - accuracy: 0.9826 - val_loss: 0.4406 - val_accuracy: 0.8762
Epoch 6/10
192/192 [==============================] - 10s 53ms/step - loss: 0.0356 - accuracy: 0.9886 - val_loss: 0.4796 - val_accuracy: 0.8703
Epoch 7/10
192/192 [==============================] - 11s 56ms/step - loss: 0.0307 - accuracy: 0.9901 - val_loss: 0.5051 - val_accuracy:

In [106]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [107]:
y_pred=model.predict(x_test)

189/189 [==============================] - 2s 7ms/step


In [108]:
y_pred=y_pred>0.5

In [109]:
confusion_matrix(y_test,y_pred)

array([[3051,  368],
       [ 435, 2181]], dtype=int64)

In [110]:
accuracy_score(y_test,y_pred)

0.8669428334714168

In [111]:
from keras.layers import Dropout

In [112]:
model1=Sequential()

In [113]:
model1.add(Embedding(input_dim=voc_size,output_dim=sentences_length,input_length=embedding_vector_features))
model1.add(Dropout(0.3))
model1.add(LSTM(units=100))
model1.add(Dropout(0.3))
model1.add(Dense(units=1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 50)            250000    
                                                                 
 dropout (Dropout)           (None, 50, 50)            0         
                                                                 
 lstm_4 (LSTM)               (None, 100)               60400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_4 (Dense)             (None, 1)                 101       
                                                                 
Total params: 310501 (1.18 MB)
Trainable params: 310501 (1.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [114]:
model1.fit(X_train,y_train,epochs=10,validation_data=(x_test,y_test),batch_size=64)

Epoch 1/10
192/192 [==============================] - 9s 39ms/step - loss: 0.3947 - accuracy: 0.8114 - val_loss: 0.2678 - val_accuracy: 0.8829
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.2053 - accuracy: 0.9204 - val_loss: 0.2697 - val_accuracy: 0.8870
Epoch 3/10
192/192 [==============================] - 7s 36ms/step - loss: 0.1522 - accuracy: 0.9436 - val_loss: 0.2871 - val_accuracy: 0.8731
Epoch 4/10
192/192 [==============================] - 7s 36ms/step - loss: 0.1159 - accuracy: 0.9595 - val_loss: 0.3413 - val_accuracy: 0.8837
Epoch 5/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0801 - accuracy: 0.9727 - val_loss: 0.4309 - val_accuracy: 0.8810
Epoch 6/10
192/192 [==============================] - 7s 36ms/step - loss: 0.0636 - accuracy: 0.9805 - val_loss: 0.4186 - val_accuracy: 0.8845
Epoch 7/10
192/192 [==============================] - 7s 39ms/step - loss: 0.0462 - accuracy: 0.9844 - val_loss: 0.4901 - val_accuracy: 0.8809

In [115]:
y_pred1=model1.predict(x_test)

189/189 [==============================] - 1s 6ms/step


In [116]:
y_pred1=y_pred1>0.5

In [117]:
confusion_matrix(y_test,y_pred1)

array([[2944,  475],
       [ 316, 2300]], dtype=int64)

In [118]:
accuracy_score(y_test,y_pred1)

0.8689312344656173